# Generated by Django 5.2 on 2025-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_first_name_alter_lead_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
